[loggers]
keys = root, InitializeSEMUtils, FileIO, SEM_ImageProcessing, InitializeGeneralUtils

[handlers]
keys = consoleHandler, FileHandler

[formatters]
keys = defaultFormatter

[logger_root]
level = DEBUG
handlers = consoleHandler, FileHandler

[logger_InitializeSEMUtils]
level = DEBUG
handlers = consoleHandler, FileHandler
qualname = InitializeSEMUtils
propagate = 0

[logger_FileIO]
level = DEBUG
handlers = consoleHandler, FileHandler
qualname = FileIO
propagate = 0

[logger_SEM_ImageProcessing]
level = DEBUG
handlers = consoleHandler, FileHandler
qualname = SEM_ImageProcessing
propagate = 0

[logger_InitializeGeneralUtils]
level = DEBUG
handlers = consoleHandler, FileHandler
qualname = InitializeGeneralUtils
propagate = 0

[handler_consoleHandler]
class = StreamHandler
level = DEBUG
formatter = defaultFormatter
args = (sys.stdout,)

[handler_FileHandler]
class = FileHandler
level = DEBUG
formatter = defaultFormatter
args = ('%(logdir)s/Microscopy_%(log_date)s.log', 'a')

[formatter_defaultFormatter]
format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt = %Y-%m-%d %H%M%S